site:
  tab: Rose Revolution
  title: Rose Revolution Dev Blog
  description: Rose Revolution is a project that aim to recreate Rose Online in Unity
  language: en
  favicon: /RoseRevolutionBlog/favicon.ico
  theme:
    light: winter
    dark: dracula
    code: github-dark
  date_format: ddd MMM DD YYYY
  blog:
    pageSize: 8
  menu:
    - id: home
      text: Home
      href: /RoseRevolutionBlog/
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About
      href: /RoseRevolutionBlog/about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /RoseRevolutionBlog/blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: All blogs
          href: /RoseRevolutionBlog/blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: Documentation
          href: /RoseRevolutionBlog/blog/category/Documentation
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: Examples
          href: /RoseRevolutionBlog/blog/category/Examples
          svg: "material-symbols:deployed-code-outline"
          target: _self
    - id: project
      text: Project
      href: /RoseRevolutionBlog/project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: contact
      text: Contact
      href: "mailto:builtbyakima@gmail.com"
      target: _blank
      svg: "material-symbols:attach-email-outline-rounded"

user:
  name: Rose Revolution Team
  site: "https://akrelia.github.io/RoseRevolutionBlog/"
  avatar: /RoseRevolutionBlog/profile.png
  sidebar:
    social:
      - href: "https://afdian.com/a/saroprock"
        ariaLabel: Support my work
        title: Support my work
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://afdian.com/a/saroprock"
        ariaLabel: Support my work
        title: Support my work
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
