site:
  tab: Rose Revolution
  title: Rose Revolution Dev Blog
  description: Rose Revolution is a project that aim to recreate Rose Online in Unity
  language: en
  favicon: /RoseRevolutionBlog/favicon.ico
  theme:
    light: winter
    dark: dracula
    code: github-dark
  date_format: ddd MMM DD YYYY
  blog:
    pageSize: 8
  menu:
    - id: home
      text: Home
      href: /RoseRevolutionBlog/
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About
      href: /RoseRevolutionBlog/about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Posts
      href: /RoseRevolutionBlog/blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
    - id: contribute
      text: Contribute
      href: /RoseRevolutionBlog/contribute
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: contact
      text: Contact
      href: "mailto:builtbyakima@gmail.com"
      target: _blank
      svg: "material-symbols:attach-email-outline-rounded"

user:
  name: Rose Revolution Team
  site: "https://akrelia.github.io/RoseRevolutionBlog/"
  avatar: /RoseRevolutionBlog/profile.png
  sidebar:
    social:
      - href: "https://discord.gg/wgBxaJ9jGt"
        ariaLabel: Our Discord Server
        title: Our Discord Server
        svg: "ri:discord-line"
      - href: "https://github.com/Akrelia"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
  footer:
    social:
      - href: "https://discord.gg/wgBxaJ9jGt"
        ariaLabel: Our Discord Server
        title: Our Discord Server
        svg: "ri:discord-line"
      - href: "https://github.com/Akrelia"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
